### ISSUE TITLE
Checklist for event workflow

### ISSUE THREAD

**Issue by thenfour** [thenfour/CafeMarcheDB#225]
We should add a configurable checklist for events to support a workflow. this should not replace the "status" field, but just be a new tab that can enforce the workflow.

each checklist item can have various behaviors. examples

* Promoter contact info (required, requires text field evidence), default assigned to XYZ
* Confirmation received (from?)
* Directors confirmed (due date, multiple "OR" assignees that can approve)

Small items are also grouped together by some category.

We should be able to change the checklist without killing old data too much.

There should be a permission for who can see workflow, or evidence.

TODO (post-0.8):

- [x] **instance mutation**. this is tricky; notes added around the tab content components. basically between evaluation mutating the instance many times, and instance changes requiring re-evaluations, it's hard to keep mutations and evals under control. need a system in place.
- [x] **model mutation**. when a user node lets users edit a model value, we need to be able to save those values to either the main event model or custom fields.
- [x] **operand2 support**. field bindings currently combine "user" and "admin" work together, which means normal value binding operations (set value to model, get value from model) are combined with workflow definition admin stuff (set operand2 to value...). This needs to be separated so there are separate user vs. admin bindings. and then complete binding work for foreign singles, options, tags...
- [x] **display styles**. at very least, a readonly style in contrast to one that lets you edit the value.
